[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
json = "0.12.4"
reqwest = { version = "0.11.26", features = ["blocking"] }
serde = { version = "1.0.197", features = ["derive"] }
